In [1]:
import numpy as np

In [2]:
# column vector
c = np.array([1,2,3])
c.shape

(3,)

In [3]:
# obtaining a particular entry
c[0]

1

In [4]:
# row vector
r = np.array ([[1,2,3]])
r.shape

(1, 3)

In [5]:
# obtaining a particular entry
r[0,1]

2

In [6]:
# creating a matrix with all zeros
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [7]:
# creating a matrix with all ones
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [8]:
# creating a matrix filled with the same constant
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [9]:
np.random.random((2,2))

array([[0.77925955, 0.51133739],
       [0.6849616 , 0.47950238]])

In [13]:
A = np.array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
B = np.array([[11,12,13,14],[15,16,17,18]])
B

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [14]:
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [17]:
np.dot(A, B)

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [18]:
np.dot(B, A)

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [19]:
A = np.array(([60,5.5,1],[65,5.0,0],[55,6.0,1]))
b = np.array([66,70,78])

In [20]:
eye3 = np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
from numpy.linalg import inv
A_inv = inv(A)
A_inv

array([[ 0.08695652,  0.00869565, -0.08695652],
       [-1.13043478,  0.08695652,  1.13043478],
       [ 2.        , -1.        , -1.        ]])

In [22]:
A*A_inv

array([[ 5.21739130e+00,  4.78260870e-02, -8.69565217e-02],
       [-7.34782609e+01,  4.34782609e-01,  0.00000000e+00],
       [ 1.10000000e+02, -6.00000000e+00, -1.00000000e+00]])

In [23]:
A.dot(A_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
A_inv.dot(b)

array([ -0.43478261,  19.65217391, -16.        ])

In [25]:
# Ax+b = y 를 바로 풀어줌

from numpy.linalg import solve
solve(A,b)

array([ -0.43478261,  19.65217391, -16.        ])

A_inv를 구해서 b라는 상수 matrix와 곱을 하거나, A_inv가 중간에 쓰여서 곱셍이 되거나
최종 솔루션의 한 부분으로 들어가는 것이 대부분

A_inv 자체를 구하는 것은 할일 없음

solve함수도 역함수를 구하지 않고 바로 해결한 형태임

-> A_inv를 따로 구한다음에 곱셈을 하는 형태는 대부분 없다.

그렇게 할 수도 있다고 생각하지만 그렇지 않게되고, numerical stability라는 문제가 있음. 계산상의 오차가 커짐

sclar도 matrix의ㅐ 한 형태인데 AX=6이었으면 A=3 b=6이면 당연히 x=2 하지만 A의 inv를 취하면
1/3 sclar를 곱하여 컴퓨팅적으로 근사값을 쓸 수 밖에 없음.

In [29]:
inv(([3,0],[0,1]))

array([[0.33333333, 0.        ],
       [0.        , 1.        ]])

기계적인 numpy operation을 다루진 않음.
CS231n의 강의나 cheat sheet을 따르면 좋음